[params]
    keywords = "Schatten, Nacht, Fotographie"
    description = "Die „Digitalisierung“ der Nacht"
    logo = "/images/logo.png"
    svgIcon = "/images/favicon.svg"
    enableImageViewer = true
    enablePDFViewer = false
    copyrightYears = "MMXXVI"
    disableScale = true
    disableOpenGraph = true
    defaultScriptEntrypoint = "ts/main.ts"

  [params.preview]
      outputPrefix = "ogPreview"
      outputSuffix = ".png"
      format =  "svg"
      image = "front.png"
      source = "post"
      [params.preview.size]
          height = 630
          width = 1200
      [params.preview.svg]
          template = "./Source Files/Other/preview-template.svg"
          scale = "width"
          removeMissing = true

[params.author]
  email = 'mail@christianmahnke.de'
  name = 'Christian Mahnke'
  uri = 'http://www.wikidata.org/entity/Q137668638'
